//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A4925A_connectorEntities : DbContext
    {
        public DB_A4925A_connectorEntities()
            : base("name=DB_A4925A_connectorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Site_Acesso> Site_Acesso { get; set; }
        public virtual DbSet<Site_Mensagem> Site_Mensagem { get; set; }
        public virtual DbSet<Site_NewsLetter> Site_NewsLetter { get; set; }
        public virtual DbSet<Site_Proposta> Site_Proposta { get; set; }
    }
}
