//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Proposta
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Empresa { get; set; }
        public string Telefone { get; set; }
        public string Proposta { get; set; }
        public System.DateTime DataHora { get; set; }
    }
}
